
    create table Asociacion (
        id_asociacion bigint generated by default as identity (start with 1),
        ubicacionAsociacion_id_ubicacion bigint,
        primary key (id_asociacion)
    )

    create table Asociacion_Pregunta (
        Asociacion_id_asociacion bigint not null,
        preguntasParaAdopcion_id_pregunta bigint not null
    )

    create table Asociacion_PublicacionConChapita (
        Asociacion_id_asociacion bigint not null,
        publicacionesConChapita_id_publicacionConChapita bigint not null
    )

    create table Asociacion_PublicacionParaAdoptar (
        Asociacion_id_asociacion bigint not null,
        publicacionesParaAdoptar_id_publicacionParaAdoptar bigint not null
    )

    create table Asociacion_PublicacionParaDarEnAdopcion (
        Asociacion_id_asociacion bigint not null,
        publicacionesParaDarEnAdopcion_id_publicacionParaDarEnAdopcion bigint not null
    )

    create table Asociacion_PublicacionSinChapita (
        Asociacion_id_asociacion bigint not null,
        publicacionesSinChapita_id_publicacionSinChapita bigint not null
    )

    create table Atributo (
        id bigint generated by default as identity (start with 1),
        valor varchar(255),
        caracteristica_id_caracteristica bigint,
        primary key (id)
    )

    create table Caracteristica (
        id_caracteristica bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id_caracteristica)
    )

    create table CaracteristicaConOpciones (
        id_caracteristica bigint not null,
        primary key (id_caracteristica)
    )

    create table CaracteristicaConOpciones_Opcion (
        CaracteristicaConOpciones_id_caracteristica bigint not null,
        opciones_id_opcion bigint not null
    )

    create table CaracteristicaLibre (
        id_caracteristica bigint not null,
        primary key (id_caracteristica)
    )

    create table Contrasenia (
        id bigint generated by default as identity (start with 1),
        password varchar(255),
        primary key (id)
    )

    create table Direccion (
        id_direccion bigint generated by default as identity (start with 1),
        altura varchar(255),
        calle varchar(255),
        localidad varchar(255),
        piso varchar(255),
        provincia varchar(255),
        primary key (id_direccion)
    )

    create table Mascota (
        id_mascota bigint generated by default as identity (start with 1),
        apodo varchar(255),
        chapita varchar(255),
        edad integer,
        fotos varchar(255),
        nombre varchar(255),
        sexo varchar(255),
        tipoMascota varchar(255),
        duenioMascota_id_persona bigint,
        primary key (id_mascota)
    )

    create table MascotaPerdida (
        id_mascotaPerdida bigint generated by default as identity (start with 1),
        chapita varchar(255),
        descripcionFisica varchar(255),
        fecha varbinary(255),
        tamanioMascota varchar(255),
        tipoMascota varchar(255),
        ubicacion_id_ubicacion bigint,
        primary key (id_mascotaPerdida)
    )

    create table Mascota_Atributo (
        Mascota_id_mascota bigint not null,
        atributos_id bigint not null
    )

    create table MetodoDeContacto (
        tipo varchar(1) not null,
        id_metodo_contacto bigint generated by default as identity (start with 1),
        email varchar(255),
        nombreApellido varchar(255),
        telefono integer,
        primary key (id_metodo_contacto)
    )

    create table Opcion (
        id_opcion bigint generated by default as identity (start with 1),
        opcion varchar(255),
        primary key (id_opcion)
    )

    create table Persona (
        tipo varchar(2) not null,
        id_persona bigint generated by default as identity (start with 1),
        apellido varchar(255),
        documento integer,
        mail varchar(255),
        nombre varchar(255),
        telefono integer,
        tipoDocumento varchar(255),
        usuario_id_usuario bigint,
        direccion_id_direccion bigint,
        publicacion_id bigint,
        primary key (id_persona)
    )

    create table Persona_MetodoDeContacto (
        Persona_id_persona bigint not null,
        contactos_id_metodo_contacto bigint not null
    )

    create table Pregunta (
        id_pregunta bigint generated by default as identity (start with 1),
        preguntaParaAdoptar varchar(255),
        preguntaParaDarEnAdopcion varchar(255),
        primary key (id_pregunta)
    )

    create table Pregunta_Opcion (
        Pregunta_id_pregunta bigint not null,
        opciones_id_opcion bigint not null
    )

    create table PublicacionConChapita (
        id_publicacionConChapita bigint generated by default as identity (start with 1),
        estadoDePublicacion varchar(255),
        mascota_id_mascota bigint,
        rescatista_id_persona bigint,
        primary key (id_publicacionConChapita)
    )

    create table PublicacionMascotaPerdida (
        id bigint generated by default as identity (start with 1),
        estadoDePublicacion varchar(255),
        mascotaPerdida_id_mascotaPerdida bigint,
        rescatista_id_persona bigint,
        primary key (id)
    )

    create table PublicacionParaAdoptar (
        id_publicacionParaAdoptar bigint generated by default as identity (start with 1),
        persona_id_persona bigint,
        primary key (id_publicacionParaAdoptar)
    )

    create table PublicacionParaAdoptar_Respuesta (
        PublicacionParaAdoptar_id_publicacionParaAdoptar bigint not null,
        respuestas_id_respuesta bigint not null
    )

    create table PublicacionParaDarEnAdopcion (
        id_publicacionParaDarEnAdopcion bigint generated by default as identity (start with 1),
        mascota_id_mascota bigint,
        primary key (id_publicacionParaDarEnAdopcion)
    )

    create table PublicacionParaDarEnAdopcion_Respuesta (
        PublicacionParaDarEnAdopcion_id_publicacionParaDarEnAdopcion bigint not null,
        respuestas_id_respuesta bigint not null
    )

    create table PublicacionSinChapita (
        id_publicacionSinChapita bigint generated by default as identity (start with 1),
        estadoDePublicacion varchar(255),
        mascotaPerdida_id_mascotaPerdida bigint,
        rescatista_id_persona bigint,
        primary key (id_publicacionSinChapita)
    )

    create table Respuesta (
        id_respuesta bigint generated by default as identity (start with 1),
        valor varchar(255),
        pregunta_id_pregunta bigint,
        primary key (id_respuesta)
    )

    create table Ubicacion (
        id_ubicacion bigint generated by default as identity (start with 1),
        latitud double not null,
        longitud double not null,
        primary key (id_ubicacion)
    )

    create table Usuario (
        id_usuario bigint generated by default as identity (start with 1),
        tipoUsuario varchar(255),
        user varchar(255),
        contrasenia_id bigint,
        primary key (id_usuario)
    )

    alter table Asociacion_PublicacionConChapita 
        add constraint UK_h2ny1wg7d0ubmk3b5rqxpwesq  unique (publicacionesConChapita_id_publicacionConChapita)

    alter table Asociacion_PublicacionParaAdoptar 
        add constraint UK_lpdn057jf9jcftgoektp7u96a  unique (publicacionesParaAdoptar_id_publicacionParaAdoptar)

    alter table Asociacion_PublicacionParaDarEnAdopcion 
        add constraint UK_b5cub7d2sq3o1e0wnxefodd5s  unique (publicacionesParaDarEnAdopcion_id_publicacionParaDarEnAdopcion)

    alter table Asociacion_PublicacionSinChapita 
        add constraint UK_r155w95bjmo22dq2u0kghexom  unique (publicacionesSinChapita_id_publicacionSinChapita)

    alter table Persona_MetodoDeContacto 
        add constraint UK_61c6clh18lt80waq9mclyiur5  unique (contactos_id_metodo_contacto)

    alter table Asociacion 
        add constraint FK_pu2tv4f0t4a8ddynrx52safrd 
        foreign key (ubicacionAsociacion_id_ubicacion) 
        references Ubicacion

    alter table Asociacion_Pregunta 
        add constraint FK_6kp2xbj42oygp8y4x9nps6sgp 
        foreign key (preguntasParaAdopcion_id_pregunta) 
        references Pregunta

    alter table Asociacion_Pregunta 
        add constraint FK_i8y4j7lrjphfvmn1ic1jnlfs0 
        foreign key (Asociacion_id_asociacion) 
        references Asociacion

    alter table Asociacion_PublicacionConChapita 
        add constraint FK_h2ny1wg7d0ubmk3b5rqxpwesq 
        foreign key (publicacionesConChapita_id_publicacionConChapita) 
        references PublicacionConChapita

    alter table Asociacion_PublicacionConChapita 
        add constraint FK_byu67m9ddunmta8yo4hggd63x 
        foreign key (Asociacion_id_asociacion) 
        references Asociacion

    alter table Asociacion_PublicacionParaAdoptar 
        add constraint FK_lpdn057jf9jcftgoektp7u96a 
        foreign key (publicacionesParaAdoptar_id_publicacionParaAdoptar) 
        references PublicacionParaAdoptar

    alter table Asociacion_PublicacionParaAdoptar 
        add constraint FK_q3f1xyvbv2vt6s3em4q6fmsjj 
        foreign key (Asociacion_id_asociacion) 
        references Asociacion

    alter table Asociacion_PublicacionParaDarEnAdopcion 
        add constraint FK_b5cub7d2sq3o1e0wnxefodd5s 
        foreign key (publicacionesParaDarEnAdopcion_id_publicacionParaDarEnAdopcion) 
        references PublicacionParaDarEnAdopcion

    alter table Asociacion_PublicacionParaDarEnAdopcion 
        add constraint FK_gux8kefacpwmb08pq6y49mipd 
        foreign key (Asociacion_id_asociacion) 
        references Asociacion

    alter table Asociacion_PublicacionSinChapita 
        add constraint FK_r155w95bjmo22dq2u0kghexom 
        foreign key (publicacionesSinChapita_id_publicacionSinChapita) 
        references PublicacionSinChapita

    alter table Asociacion_PublicacionSinChapita 
        add constraint FK_arpw40jm34jkova6vun4u1oro 
        foreign key (Asociacion_id_asociacion) 
        references Asociacion

    alter table Atributo 
        add constraint FK_4gryb1t2bube3i4jkt4iyfblw 
        foreign key (caracteristica_id_caracteristica) 
        references Caracteristica

    alter table CaracteristicaConOpciones 
        add constraint FK_h2mdph6tmjmugs134cfbj2hh8 
        foreign key (id_caracteristica) 
        references Caracteristica

    alter table CaracteristicaConOpciones_Opcion 
        add constraint FK_lys82vjpggryljrsjm359s9du 
        foreign key (opciones_id_opcion) 
        references Opcion

    alter table CaracteristicaConOpciones_Opcion 
        add constraint FK_ltexjc2l8kq89nq863a7sff3c 
        foreign key (CaracteristicaConOpciones_id_caracteristica) 
        references CaracteristicaConOpciones

    alter table CaracteristicaLibre 
        add constraint FK_nxoyiu6vvre5lrift10uqat2p 
        foreign key (id_caracteristica) 
        references Caracteristica

    alter table Mascota 
        add constraint FK_kfro20rnyabuqa9pqknt4tcta 
        foreign key (duenioMascota_id_persona) 
        references Persona

    alter table MascotaPerdida 
        add constraint FK_sr1670nhyjmshiukq1qwwu0nc 
        foreign key (ubicacion_id_ubicacion) 
        references Ubicacion

    alter table Mascota_Atributo 
        add constraint FK_pjcfwaajwc55w984aex5l8wmc 
        foreign key (atributos_id) 
        references Atributo

    alter table Mascota_Atributo 
        add constraint FK_jjebpl8g7dqbei5q1xb7er3br 
        foreign key (Mascota_id_mascota) 
        references Mascota

    alter table Persona 
        add constraint FK_2e0qhbqiu2c0k4aexsh46pstr 
        foreign key (usuario_id_usuario) 
        references Usuario

    alter table Persona 
        add constraint FK_67meotx1qliyd91i08nv9cyek 
        foreign key (direccion_id_direccion) 
        references Direccion

    alter table Persona 
        add constraint FK_g6bsic43jg952k167p5nch5et 
        foreign key (publicacion_id) 
        references PublicacionMascotaPerdida

    alter table Persona_MetodoDeContacto 
        add constraint FK_61c6clh18lt80waq9mclyiur5 
        foreign key (contactos_id_metodo_contacto) 
        references MetodoDeContacto

    alter table Persona_MetodoDeContacto 
        add constraint FK_divld9g7njdy6enqvbwd61yku 
        foreign key (Persona_id_persona) 
        references Persona

    alter table Pregunta_Opcion 
        add constraint FK_l1n5f5t5kiahlhdvjjjklypk 
        foreign key (opciones_id_opcion) 
        references Opcion

    alter table Pregunta_Opcion 
        add constraint FK_qk5jrwu014xmc5p5nbw3jan5n 
        foreign key (Pregunta_id_pregunta) 
        references Pregunta

    alter table PublicacionConChapita 
        add constraint FK_t86lcfa8p1gs0nywadmpngjss 
        foreign key (mascota_id_mascota) 
        references Mascota

    alter table PublicacionConChapita 
        add constraint FK_m6qofcu0v9k0kj6jeaj0qnoc7 
        foreign key (rescatista_id_persona) 
        references Persona

    alter table PublicacionMascotaPerdida 
        add constraint FK_qosk6xvw7mg3qph4aa6eg9m3m 
        foreign key (mascotaPerdida_id_mascotaPerdida) 
        references MascotaPerdida

    alter table PublicacionMascotaPerdida 
        add constraint FK_xyx853nsc0flbl3s8te806w3 
        foreign key (rescatista_id_persona) 
        references Persona

    alter table PublicacionParaAdoptar 
        add constraint FK_cjjjml7j5j7ki4kjmp3iggtcg 
        foreign key (persona_id_persona) 
        references Persona

    alter table PublicacionParaAdoptar_Respuesta 
        add constraint FK_mep64u95x4cs1f9pj7hlfbhic 
        foreign key (respuestas_id_respuesta) 
        references Respuesta

    alter table PublicacionParaAdoptar_Respuesta 
        add constraint FK_31mrdab10w6ly4hxqrtq0y1g6 
        foreign key (PublicacionParaAdoptar_id_publicacionParaAdoptar) 
        references PublicacionParaAdoptar

    alter table PublicacionParaDarEnAdopcion 
        add constraint FK_hkqj9twg39vjjrg150rfwqg7n 
        foreign key (mascota_id_mascota) 
        references Mascota

    alter table PublicacionParaDarEnAdopcion_Respuesta 
        add constraint FK_7m9gu9b7nvh04b926uquqtyv9 
        foreign key (respuestas_id_respuesta) 
        references Respuesta

    alter table PublicacionParaDarEnAdopcion_Respuesta 
        add constraint FK_s88nhxvixcsxs7ciha1mphybd 
        foreign key (PublicacionParaDarEnAdopcion_id_publicacionParaDarEnAdopcion) 
        references PublicacionParaDarEnAdopcion

    alter table PublicacionSinChapita 
        add constraint FK_n4gc576r3qvknbrcpli2v062c 
        foreign key (mascotaPerdida_id_mascotaPerdida) 
        references MascotaPerdida

    alter table PublicacionSinChapita 
        add constraint FK_hf01d0e0ukgl3nchcbk6xic1t 
        foreign key (rescatista_id_persona) 
        references Persona

    alter table Respuesta 
        add constraint FK_q80g0uudfnbcv5pplhcarpy5d 
        foreign key (pregunta_id_pregunta) 
        references Pregunta

    alter table Usuario 
        add constraint FK_p9llycmgq4wloxq6g93r8hybl 
        foreign key (contrasenia_id) 
        references Contrasenia
